version: 0.2
phases:
  build:
    commands:
      - echo Packaging JAR file...
      - mvn clean package -Pprod -DskipTests
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - target/diyo-service.jar
  discard-paths: yes